/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package currencyconverterapp;

import java.util.Arrays;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class MainMenuClass extends javax.swing.JFrame {
    
    UserClass user = new UserClass();
    /**
     * Creates new form MainMenuClass
     */
    public MainMenuClass()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rSMetroTextPlaceHolderBeanInfo1 = new rojerusan.RSMetroTextPlaceHolderBeanInfo();
        parentPanel = new com.k33ptoo.components.KGradientPanel();
        loginPanel = new com.k33ptoo.components.KGradientPanel();
        usernameField = new rojerusan.RSMetroTextPlaceHolder();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        loginButton = new com.k33ptoo.components.KButton();
        exitButton = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        passwordField = new javax.swing.JPasswordField();
        usernameInvalidLabel = new javax.swing.JLabel();
        signUpPanel = new com.k33ptoo.components.KGradientPanel();
        usernameTextField = new rojerusan.RSMetroTextPlaceHolder();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        signUpButton = new com.k33ptoo.components.KButton();
        exitButton1 = new com.k33ptoo.components.KButton();
        passwordField2 = new javax.swing.JPasswordField();
        mainMenuPanel = new com.k33ptoo.components.KGradientPanel();
        rSLabelImage3 = new rojerusan.RSLabelImage();
        profileButton = new com.k33ptoo.components.KButton();
        logoutButton = new com.k33ptoo.components.KButton();
        historyButton = new com.k33ptoo.components.KButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AmountButton = new rojerusan.RSMetroTextPlaceHolder();
        resetButton = new com.k33ptoo.components.KButton();
        enterButton = new com.k33ptoo.components.KButton();
        toButton = new rojerusan.RSComboMetro();
        fromButton = new rojerusan.RSComboMetro();
        amountLabel = new javax.swing.JLabel();
        profilePanel = new com.k33ptoo.components.KGradientPanel();
        rSLabelImage4 = new rojerusan.RSLabelImage();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logoutButton1 = new com.k33ptoo.components.KButton();
        historyButton1 = new com.k33ptoo.components.KButton();
        mainMenuButton = new com.k33ptoo.components.KButton();
        languageButton = new rojerusan.RSComboMetro();
        fromButton2 = new rojerusan.RSComboMetro();
        toButton1 = new rojerusan.RSComboMetro();
        enterButton1 = new com.k33ptoo.components.KButton();
        historyPanel = new com.k33ptoo.components.KGradientPanel();
        rSLabelImage5 = new rojerusan.RSLabelImage();
        logoutButton2 = new com.k33ptoo.components.KButton();
        profileButton3 = new com.k33ptoo.components.KButton();
        mainMenuButton1 = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        currencyTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parentPanel.setkEndColor(new java.awt.Color(153, 153, 255));
        parentPanel.setkStartColor(new java.awt.Color(255, 255, 255));
        parentPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setkEndColor(new java.awt.Color(255, 255, 255));
        loginPanel.setkStartColor(new java.awt.Color(153, 153, 255));

        usernameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Password");

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        loginButton.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        loginButton.setkEndColor(new java.awt.Color(102, 102, 255));
        loginButton.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        loginButton.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        loginButton.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        loginButton.setkStartColor(new java.awt.Color(102, 204, 255));
        loginButton.setLabel("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loginButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        exitButton.setkEndColor(new java.awt.Color(102, 102, 255));
        exitButton.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        exitButton.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        exitButton.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        exitButton.setkStartColor(new java.awt.Color(102, 204, 255));
        exitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitButtonActionPerformed(evt);
            }
        });

        kButton3.setText("Sign Up");
        kButton3.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        kButton3.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        kButton3.setkStartColor(new java.awt.Color(102, 204, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                kButton3ActionPerformed(evt);
            }
        });

        passwordField.setToolTipText("");
        passwordField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 112, 192), 2), javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1)));
        passwordField.setCaretColor(new java.awt.Color(204, 204, 255));
        passwordField.setSelectionColor(new java.awt.Color(0, 112, 192));
        passwordField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordFieldActionPerformed(evt);
            }
        });

        usernameInvalidLabel.setForeground(new java.awt.Color(255, 51, 51));
        usernameInvalidLabel.setToolTipText("");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(rSLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordField))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usernameInvalidLabel)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(rSLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameInvalidLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        parentPanel.add(loginPanel, "card2");

        signUpPanel.setkEndColor(new java.awt.Color(153, 153, 255));
        signUpPanel.setkStartColor(new java.awt.Color(255, 255, 255));

        usernameTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usernameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                usernameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Password");

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        signUpButton.setText("Sign Up");
        signUpButton.setToolTipText("");
        signUpButton.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        signUpButton.setkEndColor(new java.awt.Color(102, 102, 255));
        signUpButton.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        signUpButton.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        signUpButton.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        signUpButton.setkStartColor(new java.awt.Color(102, 204, 255));
        signUpButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signUpButtonActionPerformed(evt);
            }
        });

        exitButton1.setText("Exit");
        exitButton1.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        exitButton1.setkEndColor(new java.awt.Color(102, 102, 255));
        exitButton1.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        exitButton1.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        exitButton1.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        exitButton1.setkStartColor(new java.awt.Color(102, 204, 255));
        exitButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitButton1ActionPerformed(evt);
            }
        });

        passwordField2.setToolTipText("");
        passwordField2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 112, 192), 2), javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1)));
        passwordField2.setCaretColor(new java.awt.Color(204, 204, 255));
        passwordField2.setSelectionColor(new java.awt.Color(0, 112, 192));
        passwordField2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(rSLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signUpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField2))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(rSLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        parentPanel.add(signUpPanel, "card3");

        mainMenuPanel.setkEndColor(new java.awt.Color(153, 153, 255));
        mainMenuPanel.setkStartColor(new java.awt.Color(255, 255, 255));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        profileButton.setText("Profile");
        profileButton.setToolTipText("");
        profileButton.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        profileButton.setkEndColor(new java.awt.Color(102, 102, 255));
        profileButton.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        profileButton.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        profileButton.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        profileButton.setkStartColor(new java.awt.Color(102, 204, 255));
        profileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                profileButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        logoutButton.setkEndColor(new java.awt.Color(102, 102, 255));
        logoutButton.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        logoutButton.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        logoutButton.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        logoutButton.setkStartColor(new java.awt.Color(102, 204, 255));
        logoutButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logoutButtonActionPerformed(evt);
            }
        });

        historyButton.setText("History");
        historyButton.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        historyButton.setkEndColor(new java.awt.Color(102, 102, 255));
        historyButton.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        historyButton.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        historyButton.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        historyButton.setkStartColor(new java.awt.Color(102, 204, 255));
        historyButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                historyButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Amount");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("From");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("To");

        AmountButton.setForeground(new java.awt.Color(32, 131, 255));
        AmountButton.setToolTipText("");
        AmountButton.setBorderColor(new java.awt.Color(32, 131, 255));

        resetButton.setText("Reset");
        resetButton.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        resetButton.setkEndColor(new java.awt.Color(255, 102, 102));
        resetButton.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        resetButton.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        resetButton.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        resetButton.setkStartColor(new java.awt.Color(255, 255, 0));
        resetButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resetButtonActionPerformed(evt);
            }
        });

        enterButton.setText("Enter");
        enterButton.setkBackGroundColor(new java.awt.Color(0, 204, 153));
        enterButton.setkEndColor(new java.awt.Color(153, 255, 153));
        enterButton.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        enterButton.setkHoverForeGround(new java.awt.Color(102, 255, 102));
        enterButton.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        enterButton.setkStartColor(new java.awt.Color(0, 153, 0));
        enterButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                enterButtonActionPerformed(evt);
            }
        });

        toButton.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ZAR", "USD" }));
        toButton.setColorBorde(new java.awt.Color(51, 102, 255));
        toButton.setColorFondo(new java.awt.Color(153, 204, 255));
        toButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        fromButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        fromButton.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USD", "ZAR" }));
        fromButton.setColorFondo(new java.awt.Color(153, 204, 255));
        fromButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fromButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fromButtonActionPerformed(evt);
            }
        });

        amountLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fromButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AmountButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainMenuPanelLayout.createSequentialGroup()
                                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainMenuPanelLayout.createSequentialGroup()
                                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainMenuPanelLayout.createSequentialGroup()
                                        .addComponent(rSLabelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(amountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 10, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSLabelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(fromButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        parentPanel.add(mainMenuPanel, "card4");

        profilePanel.setkEndColor(new java.awt.Color(153, 153, 255));
        profilePanel.setkStartColor(new java.awt.Color(255, 255, 255));

        rSLabelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Default from currency");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Default to currency");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Preferred language ");

        logoutButton1.setText("Logout");
        logoutButton1.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        logoutButton1.setkEndColor(new java.awt.Color(102, 102, 255));
        logoutButton1.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        logoutButton1.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        logoutButton1.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        logoutButton1.setkStartColor(new java.awt.Color(102, 204, 255));
        logoutButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logoutButton1ActionPerformed(evt);
            }
        });

        historyButton1.setText("History");
        historyButton1.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        historyButton1.setkEndColor(new java.awt.Color(102, 102, 255));
        historyButton1.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        historyButton1.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        historyButton1.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        historyButton1.setkStartColor(new java.awt.Color(102, 204, 255));
        historyButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                historyButton1ActionPerformed(evt);
            }
        });

        mainMenuButton.setText("Converter");
        mainMenuButton.setToolTipText("");
        mainMenuButton.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        mainMenuButton.setkEndColor(new java.awt.Color(102, 102, 255));
        mainMenuButton.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        mainMenuButton.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        mainMenuButton.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        mainMenuButton.setkStartColor(new java.awt.Color(102, 204, 255));
        mainMenuButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mainMenuButtonActionPerformed(evt);
            }
        });

        languageButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        languageButton.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Russian ", "Chinese ", "French" }));
        languageButton.setColorFondo(new java.awt.Color(153, 204, 255));
        languageButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        languageButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                languageButtonActionPerformed(evt);
            }
        });

        fromButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        fromButton2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USD", "ZAR" }));
        fromButton2.setColorFondo(new java.awt.Color(153, 204, 255));
        fromButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fromButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fromButton2ActionPerformed(evt);
            }
        });

        toButton1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ZAR", "USD" }));
        toButton1.setColorBorde(new java.awt.Color(51, 102, 255));
        toButton1.setColorFondo(new java.awt.Color(153, 204, 255));
        toButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        enterButton1.setText("Save");
        enterButton1.setkBackGroundColor(new java.awt.Color(0, 204, 153));
        enterButton1.setkEndColor(new java.awt.Color(153, 255, 153));
        enterButton1.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        enterButton1.setkHoverForeGround(new java.awt.Color(102, 255, 102));
        enterButton1.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        enterButton1.setkStartColor(new java.awt.Color(0, 153, 0));
        enterButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                enterButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(rSLabelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(historyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fromButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addComponent(toButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(historyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addComponent(fromButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(languageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(enterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        parentPanel.add(profilePanel, "card5");

        historyPanel.setkEndColor(new java.awt.Color(153, 153, 255));
        historyPanel.setkStartColor(new java.awt.Color(255, 255, 255));

        rSLabelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N

        logoutButton2.setText("Logout");
        logoutButton2.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        logoutButton2.setkEndColor(new java.awt.Color(102, 102, 255));
        logoutButton2.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        logoutButton2.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        logoutButton2.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        logoutButton2.setkStartColor(new java.awt.Color(102, 204, 255));
        logoutButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logoutButton2ActionPerformed(evt);
            }
        });

        profileButton3.setText("Profile");
        profileButton3.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        profileButton3.setkEndColor(new java.awt.Color(102, 102, 255));
        profileButton3.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        profileButton3.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        profileButton3.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        profileButton3.setkStartColor(new java.awt.Color(102, 204, 255));
        profileButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                profileButton3ActionPerformed(evt);
            }
        });

        mainMenuButton1.setText("Converter");
        mainMenuButton1.setToolTipText("");
        mainMenuButton1.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        mainMenuButton1.setkEndColor(new java.awt.Color(102, 102, 255));
        mainMenuButton1.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        mainMenuButton1.setkHoverForeGround(new java.awt.Color(102, 204, 255));
        mainMenuButton1.setkHoverStartColor(new java.awt.Color(102, 255, 255));
        mainMenuButton1.setkStartColor(new java.awt.Color(102, 204, 255));
        mainMenuButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mainMenuButton1ActionPerformed(evt);
            }
        });

        currencyTable.setBackground(new java.awt.Color(153, 204, 255));
        currencyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "From ", "To", "Amount"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        currencyTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(currencyTable);

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(historyPanelLayout.createSequentialGroup()
                        .addComponent(rSLabelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profileButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mainMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logoutButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profileButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        parentPanel.add(historyPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kButton3ActionPerformed
    {//GEN-HEADEREND:event_kButton3ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(signUpPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_signUpButtonActionPerformed
    {//GEN-HEADEREND:event_signUpButtonActionPerformed
        String username = usernameTextField.getText();
        char[] password = passwordField2.getPassword();
        String passString = new String(password);
        
        if ((!username.isEmpty())&& (!passString.isEmpty()))
        {
            user.setUsername(username);
            user.setPassword(passString);
        }
        usernameInvalidLabel.setText("");
        parentPanel.removeAll();
        parentPanel.add(loginPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitButtonActionPerformed
    {//GEN-HEADEREND:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitButton1ActionPerformed
    {//GEN-HEADEREND:event_exitButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loginButtonActionPerformed
    {//GEN-HEADEREND:event_loginButtonActionPerformed
        String username = usernameField.getText();
        char[] password = passwordField.getPassword();
        
        String passString = new String(password);
        
        if ((username.equals(user.getUsername())) && (passString.equals(user.getPassword()))) {
            System.out.println("yay");
            usernameInvalidLabel.setText("");
            parentPanel.removeAll();
            parentPanel.add(mainMenuPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
            }
        else
        {
            usernameField.setText("");
            usernameInvalidLabel.setText("Invalid username or password!");
            passwordField.setText("");
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordFieldActionPerformed
    {//GEN-HEADEREND:event_passwordFieldActionPerformed

    }//GEN-LAST:event_passwordFieldActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_profileButtonActionPerformed
    {//GEN-HEADEREND:event_profileButtonActionPerformed

        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_profileButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_logoutButtonActionPerformed
    {//GEN-HEADEREND:event_logoutButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(loginPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_historyButtonActionPerformed
    {//GEN-HEADEREND:event_historyButtonActionPerformed
        
        parentPanel.removeAll();
        parentPanel.add(historyPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_historyButtonActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_usernameTextFieldActionPerformed
    {//GEN-HEADEREND:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void passwordField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordField2ActionPerformed
    {//GEN-HEADEREND:event_passwordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField2ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetButtonActionPerformed
    {//GEN-HEADEREND:event_resetButtonActionPerformed
        amountLabel.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_enterButtonActionPerformed
    {//GEN-HEADEREND:event_enterButtonActionPerformed
       
        Object currency1 = fromButton.getSelectedItem();
        Object currency2 = toButton.getSelectedItem();
        double amount;
        
        DefaultTableModel model = (DefaultTableModel) currencyTable.getModel();
        
        try {
            amount = CurrencyConvertorTestConsole.convert(Double.parseDouble(AmountButton.getText()), currency1.toString(), currency2.toString());
            amountLabel.setText(currency2.toString() + " " + amount);
            model.addRow(new Object[]{currency1, currency2, amount});
        } catch (Exception e)
        {
            
        }
        
    }//GEN-LAST:event_enterButtonActionPerformed

    private void fromButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fromButtonActionPerformed
    {//GEN-HEADEREND:event_fromButtonActionPerformed
        
    }//GEN-LAST:event_fromButtonActionPerformed

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_logoutButton1ActionPerformed
    {//GEN-HEADEREND:event_logoutButton1ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(loginPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_logoutButton1ActionPerformed

    private void historyButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_historyButton1ActionPerformed
    {//GEN-HEADEREND:event_historyButton1ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(historyPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_historyButton1ActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mainMenuButtonActionPerformed
    {//GEN-HEADEREND:event_mainMenuButtonActionPerformed
        parentPanel.removeAll();
        parentPanel.add(mainMenuPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void languageButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_languageButtonActionPerformed
    {//GEN-HEADEREND:event_languageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_languageButtonActionPerformed

    private void fromButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fromButton2ActionPerformed
    {//GEN-HEADEREND:event_fromButton2ActionPerformed

    }//GEN-LAST:event_fromButton2ActionPerformed

    private void enterButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_enterButton1ActionPerformed
    {//GEN-HEADEREND:event_enterButton1ActionPerformed
        String fromCurrency = fromButton2.getSelectedItem().toString();
        String toCurrency = toButton1.getSelectedItem().toString();
        
        String langauge = languageButton.getSelectedItem().toString();
        
        user.setDefaultCurrencies(fromCurrency, toCurrency);
        user.setLanguage(langauge);
        
        fromButton.setSelectedItem(user.getDefaultFromCurrency());
        toButton.setSelectedItem(user.getDefaultToCurrency());
        
        parentPanel.removeAll();
        parentPanel.add(mainMenuPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_enterButton1ActionPerformed

    private void logoutButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_logoutButton2ActionPerformed
    {//GEN-HEADEREND:event_logoutButton2ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(loginPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_logoutButton2ActionPerformed

    private void profileButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_profileButton3ActionPerformed
    {//GEN-HEADEREND:event_profileButton3ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(profilePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_profileButton3ActionPerformed

    private void mainMenuButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mainMenuButton1ActionPerformed
    {//GEN-HEADEREND:event_mainMenuButton1ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(mainMenuPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_mainMenuButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void run()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new MainMenuClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMetroTextPlaceHolder AmountButton;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTable currencyTable;
    private com.k33ptoo.components.KButton enterButton;
    private com.k33ptoo.components.KButton enterButton1;
    private com.k33ptoo.components.KButton exitButton;
    private com.k33ptoo.components.KButton exitButton1;
    private rojerusan.RSComboMetro fromButton;
    private rojerusan.RSComboMetro fromButton2;
    private com.k33ptoo.components.KButton historyButton;
    private com.k33ptoo.components.KButton historyButton1;
    private com.k33ptoo.components.KGradientPanel historyPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KButton kButton3;
    private rojerusan.RSComboMetro languageButton;
    private com.k33ptoo.components.KButton loginButton;
    private com.k33ptoo.components.KGradientPanel loginPanel;
    private com.k33ptoo.components.KButton logoutButton;
    private com.k33ptoo.components.KButton logoutButton1;
    private com.k33ptoo.components.KButton logoutButton2;
    private com.k33ptoo.components.KButton mainMenuButton;
    private com.k33ptoo.components.KButton mainMenuButton1;
    private com.k33ptoo.components.KGradientPanel mainMenuPanel;
    private com.k33ptoo.components.KGradientPanel parentPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordField2;
    private com.k33ptoo.components.KButton profileButton;
    private com.k33ptoo.components.KButton profileButton3;
    private com.k33ptoo.components.KGradientPanel profilePanel;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private rojerusan.RSLabelImage rSLabelImage3;
    private rojerusan.RSLabelImage rSLabelImage4;
    private rojerusan.RSLabelImage rSLabelImage5;
    private rojerusan.RSMetroTextPlaceHolderBeanInfo rSMetroTextPlaceHolderBeanInfo1;
    private com.k33ptoo.components.KButton resetButton;
    private com.k33ptoo.components.KButton signUpButton;
    private com.k33ptoo.components.KGradientPanel signUpPanel;
    private rojerusan.RSComboMetro toButton;
    private rojerusan.RSComboMetro toButton1;
    private rojerusan.RSMetroTextPlaceHolder usernameField;
    private javax.swing.JLabel usernameInvalidLabel;
    private rojerusan.RSMetroTextPlaceHolder usernameTextField;
    // End of variables declaration//GEN-END:variables
}
